#!/bin/bash

echo "📋 Public Invite Code Validation - Migration"
echo "=========================================="
echo ""
echo "⚠️  Apply this SQL migration to enable public vendor previews"
echo ""
echo "🔗 Steps:"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select your project: daily-drop-ledger"
echo "3. Click: SQL Editor (left sidebar)"
echo "4. Click: New Query"
echo "5. Copy the SQL below and paste it into the editor"
echo "6. Click: Run (or press Ctrl+Enter)"
echo ""
echo "=========================================="
echo ""
echo "📄 Copy this entire SQL block:"
echo ""
cat supabase/migrations/20251212000003_public_invite_code_validation.sql
echo ""
echo "=========================================="
echo ""
echo "✅ After running:"
echo "   1. Refresh your browser"
echo "   2. Scan QR code or visit /connect?code=VEN-XXX"
echo "   3. Should see vendor preview WITHOUT login"
echo ""
